### PR TITLE
Polygon/Multipolygon fix

### PR DESCRIPTION
**Pull request by gmccrackin**
Fixed it so polygons and multipolygons correctly display holes.

### CODE REVIEW

**Comment by JasonSanford** [comment]
Looks great, Thanks!

I didn't  know about any specific loop direction for complex polygons.

**Comment by gmccrackin** [comment]
Someone pointed out to me that my commits were not as clear as they should have been. 

The GeoJSON specification does not currently have a direction for polygons. It looks like it may be under consideration in revision 1.1 but I am not sure when or how it will work. It does specify the first ring is the exterior and all other that follow are interior. So my commits abide by the second but make an assumption on the first. This assumption is that the program that generates the GeoJSON will use the same direction for all rings. I dont see this ever being a problem but I guess I should have mentioned it, just encase this is not always the case. 

Sorry my comment has now become longer than my commit.

**Comment by JollyGreen** [comment]
First of all, thanks for the great software!  Very well written and easy to read.  I've tested it out on a few PostGIS generated GeoJSON objects and it works great!  Relating to your previous comment, I think the standard does need to address the direction to use.  I've been using PostGIS and the ST_AsGeoJSON function and I have noticed that if a polygon has a hole, it uses the opposite direction than you chose for generating holes.  I used your example to paste in my polygon with a hole and it won't display with a hole unless I remove the ".reverse()" method when appending the path to the paths structure.

I wonder if ST_AsGeoJSON always uses the same direction?  Here is my example
{"type":"Polygon","coordinates":[
[
[-157.756,21.4],[-157.756,21.402],[-157.756,21.402],[-157.756,21.404],[-157.756,21.404],[-157.756,21.406],[-157.756,21.406],[-157.756,21.408],[-157.754,21.408],[-157.754,21.408],[-157.752,21.408],[-157.752,21.408],[-157.75,21.408],[-157.75,21.408],[-157.748,21.408],[-157.748,21.406],[-157.748,21.406],[-157.748,21.404],[-157.748,21.404],[-157.748,21.402],[-157.748,21.402],[-157.748,21.4],[-157.75,21.4],[-157.75,21.4],[-157.752,21.4],[-157.752,21.4],[-157.754,21.4],[-157.754,21.4],[-157.756,21.4]
],[
[-157.754,21.404],[-157.754,21.404],[-157.754,21.402],[-157.752,21.402],[-157.752,21.402],[-157.75,21.402],[-157.75,21.404],[-157.75,21.404],[-157.75,21.406],[-157.752,21.406],[-157.752,21.406],[-157.754,21.406],[-157.754,21.404]
]
]}

**Comment by gmccrackin** [comment]
Yeah that is definitely a problem. Right now you can not know for sure if the software you used to generate the GeoJSON has already reversed them or they still need to be reversed. Im glade you mentioned it though because I am switching to PostGIS and I am going to be relying heavily on the ST_AsGeoJSON function. I will try and create a better solution to the problem.

**Comment by gmccrackin** [comment]
https://github.com/gmccrackin/GeoJSON-to-Google-Maps/commit/265c31a8ab18a81bf0fc75a81bba805d2c6e4d40

Now the polygon and multipolygon will check the direction before they reverse any interior rings. It works with the current example, the one you provided, and some others I created on the fly. If you see any example it does not work with please tell me. It only checks the first interior ring to determine the direction of all interior rings. I did this because I didnt want to slow down huge polygons. It does however check every polygon in a multipolygon. 

Here is an example where the first two polygons are reversed. The code has to reverse the third though.

{"type":"MultiPolygon","coordinates":[
[[
[-157.756,21.4],[-157.756,21.402],[-157.756,21.402],[-157.756,21.404],[-157.756,21.404],[-157.756,21.406],[-157.756,21.406],[-157.756,21.408],[-157.754,21.408],[-157.754,21.408],[-157.752,21.408],[-157.752,21.408],[-157.75,21.408],[-157.75,21.408],[-157.748,21.408],[-157.748,21.406],[-157.748,21.406],[-157.748,21.404],[-157.748,21.404],[-157.748,21.402],[-157.748,21.402],[-157.748,21.4],[-157.75,21.4],[-157.75,21.4],[-157.752,21.4],[-157.752,21.4],[-157.754,21.4],[-157.754,21.4],[-157.756,21.4]
],[
[-157.754,21.404],[-157.754,21.404],[-157.754,21.402],[-157.752,21.402],[-157.752,21.402],[-157.75,21.402],[-157.75,21.404],[-157.75,21.404],[-157.75,21.406],[-157.752,21.406],[-157.752,21.406],[-157.754,21.406],[-157.754,21.404]
]],[[
[-157.856,21.4],[-157.856,21.402],[-157.856,21.402],[-157.856,21.404],[-157.856,21.404],[-157.856,21.406],[-157.856,21.406],[-157.856,21.408],[-157.854,21.408],[-157.854,21.408],[-157.852,21.408],[-157.852,21.408],[-157.85,21.408],[-157.85,21.408],[-157.848,21.408],[-157.848,21.406],[-157.848,21.406],[-157.848,21.404],[-157.848,21.404],[-157.848,21.402],[-157.848,21.402],[-157.848,21.4],[-157.85,21.4],[-157.85,21.4],[-157.852,21.4],[-157.852,21.4],[-157.854,21.4],[-157.854,21.4],[-157.856,21.4]
],[
[-157.854,21.404],[-157.854,21.404],[-157.854,21.402],[-157.852,21.402],[-157.852,21.402],[-157.85,21.402],[-157.85,21.404],[-157.85,21.404],[-157.85,21.406],[-157.852,21.406],[-157.852,21.406],[-157.854,21.406],[-157.854,21.404]
]],[[
[-157.856,21.41],[-157.856,21.412],[-157.856,21.412],[-157.856,21.414],[-157.856,21.414],[-157.856,21.416],[-157.856,21.416],[-157.856,21.418],[-157.854,21.418],[-157.854,21.418],[-157.852,21.418],[-157.852,21.418],[-157.85,21.418],[-157.85,21.418],[-157.848,21.418],[-157.848,21.416],[-157.848,21.416],[-157.848,21.414],[-157.848,21.414],[-157.848,21.412],[-157.848,21.412],[-157.848,21.41],[-157.85,21.41],[-157.85,21.41],[-157.852,21.41],[-157.852,21.41],[-157.854,21.41],[-157.854,21.41],[-157.856,21.41]
],[
[-157.854,21.414],
[-157.854,21.416],
[-157.852,21.416],
[-157.852,21.416],
[-157.85,21.416],
[-157.85,21.414],
[-157.85,21.414],
[-157.85,21.412],
[-157.852,21.412],
[-157.852,21.412],
[-157.854,21.412],
[-157.854,21.414],
[-157.854,21.414]
]]
]}

**Pull request merged**
