### PR TITLE
GeoJSON Feature Properties

### PR DESCRIPTION
**Pull request by ghost**
Found it useful to add properties of feature objects to googleObj equivalents.

### CODE REVIEW

**Comment by JasonSanford** [comment]
Cool, thanks for adding this. I wonder if it would be a good idea to look for properties in a GeoJSON Feature as well.

```
{
    "type": "Feature",
    "geometry": {
        "type": "Point",
        "coordinates": [-82.3456, 35.6785]
    },
    "properties": {
        "myKey": "myValue",
        "myKey2": "myValue2"
    }
}
```

**Comment by ghost** [comment]
Thanks, added this for a project I'm working on and happy to contribute here if useful. 

It should work for Feature, and all geometry types within inherit the Feature's properties. In the index.htm example, clicking on the vectors of any of the Feature examples will dump their properties into an infowindow for view.

**Comment by JasonSanford** [comment]
Ahhh, ok cool. I guess I should have tested that. :-) Out of town ... Will
pull soon.

**Comment by ghost** [comment]
Awesome, and thanks for sharing this library.

**Comment by JasonSanford** [comment]
I had no clue you could set arbitrary key value pairs on a Google Maps vector. This way the GeoJSON properties are there and the user can do what they want with them (infowindow or other property display) when a feature is selected. This is great stuff. Thanks!

**Pull request merged**
